<?php
/**
 * Plugin configuration interface
 *
 * @package Email SMTP
 */

require_once 'ProgramFunctions/SendEmail.fnc.php';

// Check the script is called by the right program & plugin is activated.
if ( $_REQUEST['modname'] !== 'School_Setup/Configuration.php'
	|| ! $RosarioPlugins['Email_SMTP']
	|| $_REQUEST['modfunc'] !== 'config' )
{
	$error[] = _( 'You\'re not allowed to use this program!' );

	echo ErrorMessage( $error, 'fatal' );
}


// Update SQL.
if ( is_null( Config( 'EMAIL_SMTP_PAUSE' ) ) )
{
	// @deprecated since version 2.0 (2022.01).
	DBQuery( "INSERT INTO config (school_id, title, config_value)
	SELECT DISTINCT sch.id, 'EMAIL_SMTP_PAUSE', '0'
	FROM schools sch
	WHERE NOT EXISTS (SELECT title
		FROM config
		WHERE title='EMAIL_SMTP_PAUSE');
	INSERT INTO config (school_id, title, config_value)
	SELECT 0, 'EMAIL_SMTP_PAUSE', '0';" );
}

// Note: no need to call ProgramTitle() here!

if ( isset( $_REQUEST['save'] )
	&& $_REQUEST['save'] === 'true' )
{
	if ( $_REQUEST['values']['config']
		&& $_POST['values']
		&& AllowEdit() )
	{
		// Update the config table.
		$sql = '';

		if ( isset( $_REQUEST['values']['config'] )
			&& is_array( $_REQUEST['values']['config'] ) )
		{
			foreach ( (array) $_REQUEST['values']['config'] as $column => $value )
			{
				if ( $column === 'EMAIL_SMTP_PORT' )
				{
					// Sanitize port (positive int).
					$value = preg_replace( '/[^0-9]/', '', $value );
				}

				$sql .= "UPDATE config
					SET CONFIG_VALUE='" . $value . "'
					WHERE TITLE='" . $column . "'
					AND SCHOOL_ID IN('" . UserSchool() . "','0');"; // Save for all schools too.
			}
		}

		if ( $sql != '' )
		{
			DBQuery( $sql );

			$note[] = button( 'check' ) . '&nbsp;' . _( 'The plugin configuration has been modified.' );
		}

		unset( $_ROSARIO['Config'] ); // Update Config var.
	}

	if ( filter_var( $_REQUEST['test-email'], FILTER_VALIDATE_EMAIL ) )
	{
		$to = $_REQUEST['test-email'];
		$subject_test = sprintf( dgettext( 'Email_SMTP', 'Test email to %s' ), $to );
		$subject = 'Email SMTP: ' . $subject_test;
		$msg = dgettext( 'Email_SMTP', 'This is a test email generated by the Email SMTP RosarioSIS plugin.' );

		$sent = SendEmail(
			$to,
			$subject,
			$msg
		);

		if ( ! $sent )
		{
			$error[] = $subject_test . ': ' . _( 'Fail' );
		}
		else
		{
			$note[] = $subject_test . ': ' . _( 'Success' );
		}

		// Unset test & redirect URL.
		RedirectURL( 'test-email' );
	}

	if ( function_exists( 'RedirectURL' ) )
	{
		// Unset save & values & redirect URL.
		RedirectURL( [ 'save', 'values' ] );
	}
}

if ( empty( $_REQUEST['save'] )
	&& empty( $_REQUEST['remove'] ) )
{
	echo '<form action="' . ( function_exists( 'URLEscape' ) ?
		URLEscape( 'Modules.php?modname=' . $_REQUEST['modname'] . '&tab=plugins&modfunc=config&plugin=Email_SMTP&save=true' ) :
		_myURLEncode( 'Modules.php?modname=' . $_REQUEST['modname'] . '&tab=plugins&modfunc=config&plugin=Email_SMTP&save=true' ) ) . '" method="POST">';

	DrawHeader( '', SubmitButton( _( 'Save' ) ) );

	echo ErrorMessage( $note, 'note' );

	echo ErrorMessage( $error, 'error' );

	echo '<br />';

	$school_title = '';

	// If more than 1 school, add its title to table title.
	if ( SchoolInfo( 'SCHOOLS_NB' ) > 1 )
	{
		$school_title = SchoolInfo( 'SHORT_NAME' );

		if ( ! $school_title )
		{
			// No short name, get full title.
			$school_title = SchoolInfo( 'TITLE' );
		}

		$school_title = '(' . $school_title . ')';
	}

	PopTable(
		'header',
		sprintf(
			dgettext( 'Email_SMTP', 'Email SMTP %s' ),
			$school_title
		)
	);

	$tooltip = '<div class="tooltip"><i>' . dgettext(
		'Email_SMTP',
		'If you are sending using an email provider (Gmail, Yahoo, Hotmail, Outlook.com, etc) this setting should be your email address for this account.'
	) . '</i></div>';

	// From email.
	echo '<table class="width-100p"><tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_FROM' ),
		'values[config][EMAIL_SMTP_FROM]',
		dgettext( 'Email_SMTP', 'From Email' ) . $tooltip,
		'type="email" size="20"',
		false
	) . '</td></tr>';

	$tooltip = '<div class="tooltip"><i>' . sprintf( dgettext(
		'Email_SMTP',
		'You can specify the name that emails should be sent from. If you leave this blank, the emails will be sent from %s.'
	), Config( 'NAME' ) ) . '</i></div>';

	// From name.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_FROM_NAME' ),
		'values[config][EMAIL_SMTP_FROM_NAME]',
		dgettext( 'Email_SMTP', 'From Name' ) . $tooltip,
		'size="20" placeholder="' . ( function_exists( 'AttrEscape' ) ? AttrEscape( Config( 'NAME' ) ) : htmlspecialchars( Config( 'NAME' ), ENT_QUOTES ) ) . '"',
		false
	) . '<hr/></td></tr>';

	// Host.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_HOST' ),
		'values[config][EMAIL_SMTP_HOST]',
		dgettext( 'Email_SMTP', 'SMTP Host' ),
		'required',
		false
	) . '</td></tr>';

	// Port.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_PORT' ),
		'values[config][EMAIL_SMTP_PORT]',
		dgettext( 'Email_SMTP', 'SMTP Port' ),
		'type="number" min="0" required placeholder="587"',
		false
	) . '</td></tr>';

	$encryption_options = [
		'ssl' => 'SSL',
		'tls' => 'TLS',
	];

	// Encryption.
	echo '<tr><td>' . SelectInput(
		Config( 'EMAIL_SMTP_ENCRYPTION' ),
		'values[config][EMAIL_SMTP_ENCRYPTION]',
		dgettext( 'Email_SMTP', 'Encryption' ),
		$encryption_options,
		_( 'None' ),
		'',
		false
	) . '</td></tr>';

	// Username.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_USERNAME' ),
		'values[config][EMAIL_SMTP_USERNAME]',
		_( 'Username' ),
		'size="20"',
		false
	) . '</td></tr>';

	// Password.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_PASSWORD' ),
		'values[config][EMAIL_SMTP_PASSWORD]',
		_( 'Password' ),
		'size="20" type="password"',
		false
	) . '</td></tr>';

	$tooltip = '<div class="tooltip"><i>' . dgettext(
		'Email_SMTP',
		'If you are sending more than 50 emails at once and receive an SMTP error, adding a pause between each email may help.'
	) . '</i></div>';

	// Pause between each email.
	echo '<tr><td>' . TextInput(
		Config( 'EMAIL_SMTP_PAUSE' ),
		'values[config][EMAIL_SMTP_PAUSE]',
		dgettext( 'Email_SMTP', 'Pause between each email (seconds)' ) . $tooltip,
		'type="number" min="0" max="30" required placeholder="2"',
		false
	) . '<hr /></td></tr>';

	echo '<tr><td>' . TextInput(
		'',
		'test-email',
		dgettext( 'Email_SMTP', 'Send a test email To' ),
		'type="email" size="20"',
		false
	) . '<br />' . SubmitButton( dgettext( 'Email_SMTP', 'Send Test' ), '', '' ) . '</td></tr>';

	echo '</table>';

	PopTable( 'footer' );

	echo '<br /><div class="center">' . SubmitButton( _( 'Save' ) ) . '</div></form>';
}
